name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/github-snake.yml

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - name: Generate snake.gif
        uses: Platane/snk@v3
        with:
          github_user_name: ayyappa3232
          outputs: |
            dist/snake.gif?color_snake=00e5ff&color_dots=#3d4460,#0e4429,#006d32,#26a641,#39d353&color_background=12103a

      - name: Push snake.gif to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
